######################################################################
# Automatically generated by qmake (3.0) ?? ????. 26 10:29:17 2018
######################################################################

TEMPLATE = app
TARGET = Qt
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT+=widgets
